// <auto-generated />
using Fbs_webApi_v1.Db_FbsContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fbs_webApi_v1.Migrations
{
    [DbContext(typeof(FbsContext))]
    partial class FbsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fbs_webApi_v1.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            User_Id = 1,
                            Email = "dummy1@gmail.com",
                            Name = "dummy1",
                            PhoneNumber = "789654134",
                            password = "asdf@1223"
                        },
                        new
                        {
                            User_Id = 2,
                            Email = "dummy4@gmail.com",
                            Name = "dummy4",
                            PhoneNumber = "789654134",
                            password = "asdf@4443"
                        },
                        new
                        {
                            User_Id = 3,
                            Email = "dummy3@gmail.com",
                            Name = "dummy3",
                            PhoneNumber = "789648534",
                            password = "asdf@3333"
                        },
                        new
                        {
                            User_Id = 4,
                            Email = "dummy2@gmail.com",
                            Name = "dummy2",
                            PhoneNumber = "789654789",
                            password = "asdf@1123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
